version: '3.8'

services:
  app:
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    command: >
      sh -c "php-fpm"
    ports:
      - "9000:9000"

  webserver:
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8000:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

  db:
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=sidequest_crm
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=secret
      - MYSQL_USER=sidequest_crm
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

  redis:
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  mailhog:
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local
