version: '3.8'

services:
  app:
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    command: >
      sh -c "php-fpm"
    ports:
      - "9000:9000"

  webserver:
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "${DOCKER_WEB_PORT:-8000}:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

  db:
    ports:
      - "${DOCKER_DB_PORT:-3306}:3306"
    environment:
      - MYSQL_DATABASE=${DOCKER_DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DOCKER_DB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${DOCKER_DB_PASSWORD}
      - MYSQL_USER=${DOCKER_DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

  redis:
    ports:
      - "${DOCKER_REDIS_PORT:-6379}:6379"
    volumes:
      - redisdata:/data

  mailhog:
    ports:
      - "${DOCKER_MAILHOG_SMTP_PORT:-1025}:1025"
      - "${DOCKER_MAILHOG_UI_PORT:-8025}:8025"

volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local
