version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sidequest_crm_app
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - sidequest_crm_network

  webserver:
    image: nginx:alpine
    container_name: sidequest_crm_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - sidequest_crm_network

  db:
    image: mysql:8.0
    container_name: sidequest_crm_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sidequest_crm
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: sidequest_crm
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - dbdata:/var/lib/mysql
    networks:
      - sidequest_crm_network

  redis:
    image: redis:alpine
    container_name: sidequest_crm_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - sidequest_crm_network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: sidequest_crm_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - sidequest_crm_network

networks:
  sidequest_crm_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
