version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sidequest_crm_app
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - "${DOCKER_APP_PORT:-5173}:5173"
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - sidequest_crm_network

  webserver:
    image: nginx:alpine
    container_name: sidequest_crm_nginx
    restart: unless-stopped
    ports:
      - "${DOCKER_WEB_PORT:-8000}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - sidequest_crm_network

  db:
    image: mysql:8.0
    container_name: sidequest_crm_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DOCKER_DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DOCKER_DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DOCKER_DB_PASSWORD}
      MYSQL_USER: ${DOCKER_DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "${DOCKER_DB_PORT:-3306}:3306"
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - dbdata:/var/lib/mysql
    networks:
      - sidequest_crm_network

  redis:
    image: redis:alpine
    container_name: sidequest_crm_redis
    restart: unless-stopped
    ports:
      - "${DOCKER_REDIS_PORT:-6379}:6379"
    networks:
      - sidequest_crm_network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: sidequest_crm_mailhog
    restart: unless-stopped
    ports:
      - "${DOCKER_MAILHOG_SMTP_PORT:-1025}:1025"
      - "${DOCKER_MAILHOG_UI_PORT:-8025}:8025"
    networks:
      - sidequest_crm_network

networks:
  sidequest_crm_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
