name: SideQuest CRM Tests

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  sidequest-crm-tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, bcmath, gd, zip, curl, fileinfo, openssl, tokenizer, xmlwriter, dom, xmlreader, libxml, filter, session, hash, json, spl, reflection, standard, date, calendar, pcre, ftp, gettext, iconv, mbstring, pcntl, shmop, sockets, sysvmsg, sysvsem, sysvshm, wddx, xml, xmlreader, xmlwriter, xsl, zlib, ctype, curl, dom, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, libxml, mbstring, openssl, pcre, pdo, phar, posix, session, shmop, simplexml, snmp, soap, sockets, spl, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, zlib
        coverage: xdebug

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Composer dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Directory permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Configure environment
      run: |
        echo "APP_ENV=testing" >> .env
        echo "APP_DEBUG=true" >> .env
        echo "APP_KEY=base64:$(openssl rand -base64 32)" >> .env
        echo "DB_CONNECTION=sqlite" >> .env
        echo "DB_DATABASE=:memory:" >> .env
        echo "CACHE_DRIVER=array" >> .env
        echo "SESSION_DRIVER=array" >> .env
        echo "QUEUE_CONNECTION=sync" >> .env
        echo "MAIL_MAILER=array" >> .env
        echo "REDIS_HOST=127.0.0.1" >> .env
        echo "REDIS_PASSWORD=null" >> .env
        echo "REDIS_PORT=6379" >> .env

    - name: Clear and cache config
      run: php artisan config:clear

    - name: Run database migrations
      run: php artisan migrate --force

    - name: Run tests
      run: php artisan test

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: sidequest-crm-coverage
        fail_ci_if_error: false
        verbose: true
